### PR TITLE
[gh-14] Add infrastructure diagram

### LINKED ISSUE #14: [Chore] As a user, I can see the infrastructure document
## Why

The Infrastructure document helps others have a general and comprehensive knowledge of how our system structures and works.

## Acceptance Criteria

- The document should contain detailed system requirements
- The document should list the necessary configuration steps

### PR DESCRIPTION
**Pull request by nvminhtue**
- Close #14 

## What happened 👀

Add wikis and the infrastructure diagram to describe the planned system

## Insight 📝

- 2 wiki pages `Home` and `Infrastructure-Diagram` are added, they will be published in the following CI PR.
- The diagram is manually drawn by LucidChart

## Proof Of Work 📹

Infrastructure diagram

### CODE REVIEW

**Comment by liamstevens111** [comment]
@nvminhtue 

- Can we rename the bucket part to include the service name from AWS like other, ie `S3` 
- What about moving the `VPC` label to the top of the VPC parameter so it's easier to see (near gateway)
- Shall we show two different availability zones in diagram - with Fargate in each
- Shall we show the public and private subnet for each? I think we will have at least 4 ie 10.0.1.0/24 10.0.2.0/24 10.0.3.0/24 10.0.4.0/24. I think private subnets need a NAT gateway as well
- Let’s move bastion server (ec2 instance?) outside of ECS


AWS Links regarding Subnets and VPC:
- https://docs.aws.amazon.com/vpc/latest/userguide/vpc-example-private-subnets-nat.html
- https://docs.aws.amazon.com/vpc/latest/userguide/configure-subnets.html

**Comment by nvminhtue** [comment]
> @nvminhtue
> 
> * Can we rename the bucket part to include the service name from AWS like other, ie `S3`
> * What about moving the `VPC` label to the top of the VPC parameter so it's easier to see (near gateway)
> * Shall we show two different availability zones in diagram - with Fargate in each
> * Shall we show the public and private subnet for each? I think we will have at least 4 ie 10.0.1.0/24 10.0.2.0/24 10.0.3.0/24 10.0.4.0/24. I think private subnets need a NAT gateway as well
> * Let’s move bastion server (ec2 instance?) outside of ECS
> 
> AWS Links regarding Subnets and VPC:
> 
> * [docs.aws.amazon.com/vpc/latest/userguide/vpc-example-private-subnets-nat.html](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-example-private-subnets-nat.html)
> * [docs.aws.amazon.com/vpc/latest/userguide/configure-subnets.html](https://docs.aws.amazon.com/vpc/latest/userguide/configure-subnets.html)

Thanks @liamstevens111, I updated the diagram shown in the description, please help me to check it once again

**Comment by liamstevens111** [comment]
> > @nvminhtue
> Thanks @liamstevens111, I updated the diagram shown in the description, please help me to check it once again

@nvminhtue 

Yeah looking good now. One more suggestion though:
- We can have `1` LoadBalancer going to both of the public subnets
- Maybe just `1` bastion server

Think that's good then 👍  If you wanted to go extra you could add
- Nat Gateway in each of the two public subnet
- Arrow/lines showing Bastion can talk to EC and DB in the private network

**Comment by nvminhtue** [comment]
> > > @nvminhtue
> > > Thanks @liamstevens111, I updated the diagram shown in the description, please help me to check it once again
> 
> @nvminhtue
> 
> Yeah looking good now. One more suggestion though:
> 
> * We can have `1` LoadBalancer going to both of the public subnets
> * Maybe just `1` bastion server
> 
> Think that's good then 👍 If you wanted to go extra you could add
> 
> * Nat Gateway in each of the two public subnet
> * Arrow/lines showing Bastion can talk to EC and DB in the private network

Updated @liamstevens111

**Review by liamstevens111 — APPROVED** [review]
I only see one public subnet now 😛 

Approved for now.


p.s my previous comment regarding NAT Gateway in each public subnet I don't think is technically needed as I don't think the elixir/phoenix application you will be hosting in ECS needs to talk to public internet. 🤔

**Comment by bterone** [comment]
@nvminhtue Do we intend to have elastic cache in each availability zone? In easyhotel, we only ever needed one that is shared 🤔 

Also, shall we add the auto-scaling icon to the diagram as well? So its more clear which resources we intend to scale.

**Review by bterone — APPROVED** [review]
Aside from the comments, LGTM

**Comment by nvminhtue** [comment]
@liamstevens111 @bterone I update the diagram to add
- missing public subnet in 1b AZ
- Move the ElastiCache to shared components and link with Bastion Host
- Add the ASG on Reader instances

**Pull request merged**
